version: 2.1

orbs:
  node: circleci/node@5.2
  coveralls: coveralls/coveralls@2.2.5

jobs:
  lint:
    working_directory: ~/project
    docker:
      - image: cimg/node:24.20.0
    steps:
      - checkout
      - node/install:
          node-version: '24.20.0'
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Lint
          command: npm run lint
  test:
    working_directory: ~/project
    docker:
      - image: cimg/node:24.20.0
    steps:
      - checkout
      - node/install:
          node-version: '24.20.0'
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Test
          command: npm test -- --coverage
      - coveralls/upload
  semgrep:
    docker:
        - image: returntocorp/semgrep
    steps:
      - checkout
      - run:
          name: Check code against community-provided and custom semgrep rules
          command: semgrep ci --config auto

workflows:
  test:
    jobs:
      - test
      - lint
      - semgrep
